eureka:
  client:
    serviceUrl:
      defaultZone: http://www.yyuming.vip:8888/eureka/
  instance:
      prefer-ip-address: true
server:
  port: 8763 #会员服务的端口


spring:
  application:
    name: service-member  #会员服务的名称
